# Generated by Django 4.1.5 on 2023-02-01 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_detail',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
