# Generated by Django 4.1.5 on 2023-02-01 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_detail_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_detail',
            old_name='Order',
            new_name='order',
        ),
    ]
